version: '3.1'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8099:8099"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=0000
    volumes:
      - .:/app

  db:
    image: postgres:latest
    ports:
      - "8100:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000
      - POSTGRES_DB=postgres
